/**
 * CC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatalogDto { 
    id?: number | null;
    parentId?: number | null;
    name?: string | null;
    showName?: string | null;
    abbreviation?: string | null;
    value?: string | null;
    description?: string | null;
    isParent?: boolean;
    isActive?: boolean;
    isDeleted?: boolean;
    children?: Array<CatalogDto> | null;
}

