/**
 * CC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateFeatureRequest { 
    name?: string | null;
    showName?: string | null;
    path?: string | null;
    icon?: string | null;
}

