/**
 * CC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectApiKeyDto } from './projectApiKeyDto';


export interface ProjectDto { 
    id?: string | null;
    name?: string | null;
    showName?: string | null;
    description?: string | null;
    isActive?: boolean;
    apiKeys?: Array<ProjectApiKeyDto> | null;
    catalogIds?: Array<number> | null;
}

