/**
 * CC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectApiKeyDto { 
    id?: number | null;
    title?: string | null;
    description?: string | null;
    key?: string | null;
    expirationDate?: string | null;
    isIndefinite?: boolean;
    allowedIp?: string | null;
    allowedDomain?: string | null;
    isDeleted?: boolean;
}

