/**
 * CC API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: string | null;
    userName?: string | null;
    email?: string | null;
    password?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    roleId?: string;
    roleName?: string | null;
    isDeleted?: boolean;
}

